name: CI Pipeline

on:
  push:
    branches: [ "main", "import-aiand" ]   # Run on pushes to these branches
  pull_request:
    branches: [ "main" ]                   # Run on PRs targeting main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run lint (if you have ESLint)
      - name: Lint code
        run: npm run lint --if-present

      # 5. Run tests (if you have Jest/React Testing Library)
      - name: Run tests
        run: npm test -- --watchAll=false

      # 6. Build project
      - name: Build project
        run: npm run build
